spring.application.name=ImageDemo
spring.ai.openai.api-key=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
